version: "3"
networks:
  test-network:
    driver: bridge
services:
  test-frontend:
    image: test-frontend
    container_name: test-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/usr/src/app/
    networks:
      - test-network
    depends_on:
      - test-backend
    environment:
      CHOKIDAR_USEPOLLING: true
    command: ["npm", "run",  "dev"]
  test-backend:
    image: test-backend
    container_name: test-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/usr/src/app
    networks:
      - test-network
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-dp(-2k_6x$@%ligra!w(o85c1^xrjypv6gaazy5ev*k35ym&4f
      - ALLOWED_HOSTS=localhost,127.0.0.1
